[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
solana_coin_flip = "2gJ8CLYn4n1SkwHWivLqyePSGCXs8g8CKZj5nGTx8jbE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/thomascadle/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
